### ISSUE TITLE
using World space configuration result in people connecting to host having loaded mods in user root

### ISSUE THREAD

**Issue by epicEaston197** [EIA485/NeosExposePatchedMethods#3]
basically if I have the World space configuration on when I'm hosting anybody connecting to me it will have "loaded mods" in their user root and will show what mods I have 
because the host generates the user root
![image](https://user-images.githubusercontent.com/76523692/172188321-c6d960c4-4f0a-471b-861e-9d47e6afd1ab.png)

**Comment by EIA485** [comment]
fixed in version [3.0.0.0](https://github.com/EIA485/NeosExposePatchedMethods/releases/tag/3.0.0.0)
